import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GitHub Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="font-sans bg-slate-900 text-white">
        <header>
          <nav className="text-white">
          <h1 className="text-4xl md:text-6xl lg:text-6xl font-bold text-center text-white pt-5">
        GitHub Finder
      </h1>          </nav>
        </header>
        {children}
        
        
      </body>
    </html>
  );
}
